### ISSUE TITLE
Unreadable Menu Text

### ISSUE THREAD

**Issue by srtopster** [MC-U-Team/Music-Player#267] opened 2021-08-19 22:42 UTC
![image](https://user-images.githubusercontent.com/85837528/130153435-f145199a-cf8e-46a7-b264-bcb79a70e152.png)

- Mod version: 2.1.1.136
- Minecraft version: 1.8.9
- Forge version: 8.0.99.99
- UTeamCore version: 1.3.0.63

**Comment by HyCraftHD** [comment] 2022-01-09 23:31
Duplicate of #55

**Closed as completed by HyCraftHD** 2022-01-09 23:31 UTC
Labels: bug
