### ISSUE TITLE
[1.8.9] Crashing With Patcher

### ISSUE THREAD

**Issue by CodWafer** [MC-U-Team/Music-Player#266] opened 2021-08-18 21:49 UTC
**Describe the bug**
When I launch minecraft with opitifine AND patcher installed, it crashes the game upon starting. (Optifine doesn't cause the crash, however patcher is an optifine add on)

**To Reproduce**
1. Download Music Player 2.1.1.136
2. Download OptiFine_1.8.9_HD_U_M5
3. Download Patcher 1.5.1 (1.8.9) (https://sk1er.club/mods/patcher)

**Expected behavior**
That Minecraft launches, and I have all mods installed

**Screenshots**
It crashes on startup, cannot get a screenshot

**Versions**
- Mod version: 2.1.1.136
- Minecraft version: 1.8.9
- Forge version: 11.15.1.2318
- UTeamCore version: Versian 1.8.9 dosn't require UTeamCore-I do not have it installed

**Log (if crash occures)**
https://paste.ee/p/5bpbP

**Comment by HyCraftHD** [comment] 2021-08-18 21:59
Remove patcher. This mod breaks some stuff and it will/can not be fixed.
Duplicate of #254 #109 #63

**Closed as completed by HyCraftHD** 2021-08-18 21:59 UTC
Labels: bug

**Comment by HyCraftHD** [comment] 2022-06-21 23:41
Should be fixed with this version https://www.curseforge.com/minecraft/mc-mods/music-player/files/3841508
