### ISSUE TITLE
text is bugged

### ISSUE THREAD

**Issue by malleux** [MC-U-Team/Music-Player#276] opened 2021-11-28 13:07 UTC
![2021-11-28_13 45 32](https://user-images.githubusercontent.com/83955257/143769046-a83e53cc-db09-4272-9897-a46e1c074b6a.png) 

is this supposed to happen?

**Comment by HyCraftHD** [comment] 2021-11-28 14:17
No that's not supposed to happen.
What's your minecraft version?

_It's generally a good idea to follow the bug report template_

**Comment by kennyL07** [comment] 2021-11-28 22:21
I also have this problem
mod version: 1.8.9-2.1.1.136
mc version: 1.8.9
forge: 1.8.9-11.15.1.2318
Uteam Core: 1.8.9-1.3.0.63

**Comment by HyCraftHD** [comment] 2021-12-02 15:44
Seems like this is a duplicate of #55 (Issue with optifine probably)
As 1.8.9 is too old this will probably not be fixed. In the linked issue there is a resource pack that you can use to fix that issue.

**Closed as completed** 2022-01-09 23:26 UTC
Labels: bug
