### ISSUE TITLE
[1.14.4] Crash on startup related to classdef not found PlayerTickEvent

### ISSUE THREAD

**Issue by chickenbiscuts** [MC-U-Team/Music-Player#17] opened 2019-08-13 18:22 UTC
I got another crash for 1.14
[crash-2019-08-13_14.17.19-client.txt](https://github.com/MC-U-Team/Music-Player/files/3498327/crash-2019-08-13_14.17.19-client.txt)

I use the new version of this mod, and it's still crashing

**Comment by HyCraftHD** [comment] 2019-08-13 18:25
The issue is caused by an other mod:
`at com.mamiyaotaru.voxelmap.forgemod.ClientProxy.postInit(ClientProxy.java:19) ~[?:1.0] {}`
Please report to VoxelMap or update if there is an update available.

**Comment by chickenbiscuts** [comment] 2019-08-13 18:27
alright let  me go remove that mod

**Comment by MrTroble** [comment] 2019-08-13 18:28
I bet that this mod is outdated to.
So you could try updating it.

Closing this issue.

Cheers
~MrTroble

**Closed as completed by MrTroble** 2019-08-13 18:28 UTC
