### ISSUE TITLE
It keeps skipping youtube songs [1.20.1 Forge] 

### ISSUE THREAD

**Issue by Sockjr07** [MC-U-Team/Music-Player#1101] opened 2024-07-31 19:15 UTC
### Bug description and reproduction steps

I have no clue how to trigger this. I was using it yesterday and it was fine. I log on today and it started doing this. I did not add any mods that interfere with this one. It still plays songs that I have installed locally just fine but when I try to play a song from my youtube playlist it does this. Idk if it is relevant or not but I am playing on a steam deck on the prism launcher. 

### Log files and Screenshots

https://github.com/user-attachments/assets/252c7785-1f86-432d-a309-5e97b192580e

### Used minecraft version

1.20.x

### Used forge or fabric version

47.3.0

### Used mod version

2.7.0.267

**Comment by SwissCoda** [comment] 2024-07-31 22:35
Just wanted to add I've also been having the same issue as well, so it's likely safe to say it's not something exclusively on your end

**Comment by Spacedestructor** [comment] 2024-08-01 02:10
i have the same problem in minecraft 1.18.2 and it looks like a duplicate of [this issue](https://github.com/MC-U-Team/Music-Player/issues/1100) someone else opened who described the same thing.

**Comment by Sockjr07** [comment] 2024-08-01 03:54
> i have the same problem in minecraft 1.18.2 and it looks like a duplicate of [this issue](https://github.com/MC-U-Team/Music-Player/issues/1100) someone else opened who described the same thing.

They are similar issues, but if you look at the two videos you will notice that in mine the tracks will automatically move on to the next. The other video the track just wouldn't play.

**Comment by Fyoncle** [comment] 2024-08-01 12:09
> > i have the same problem in minecraft 1.18.2 and it looks like a duplicate of [this issue](https://github.com/MC-U-Team/Music-Player/issues/1100) someone else opened who described the same thing.
> 
> They are similar issues, but if you look at the two videos you will notice that in mine the tracks will automatically move on to the next. The other video the track just wouldn't play.

Because the playback on loop in the other video.

**Comment by HyCraftHD** [comment] 2024-08-01 13:45
Fixed with these versions: 
![image](https://github.com/user-attachments/assets/d3d1fcb5-ac5a-4ca9-96f7-4a4d536f22b3)

**Comment by Fyoncle** [comment] 2024-08-01 13:45
> Fixed with these versions: ![image](https://private-user-images.githubusercontent.com/7681220/354249371-d3d1fcb5-ac5a-4ca9-96f7-4a4d536f22b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjAyNDUsIm5iZiI6MTcyMjUxOTk0NSwicGF0aCI6Ii83NjgxMjIwLzM1NDI0OTM3MS1kM2QxZmNiNS1hYzVhLTRjYTktOTZmNy00YTRkNTM2ZjIyYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMTM0NTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEwZjc0OTI0NGRmZTMzM2NiMDQyMWRkMGI4YzY0ZTI4ODNmMGE2ZTg2NjM3ZWFmM2Q4YzA5MzM0ZWUzMGVhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9Yi7Mi73NYA_QfhnjNQML08M5GpmR82i3NZuEWEVsBE)

Thanks O7

**Closed as completed by HyCraftHD** 2024-08-01 13:45 UTC
Labels: bug
