### ISSUE TITLE
Fabric Port

### ISSUE THREAD

**Issue by just-chubbyfoxx** [MC-U-Team/Music-Player#277] opened 2021-11-30 18:22 UTC
It would be interesting to see, the mod has 700k+ downloads and there arent any mods similar to this whatsoever on fabric. You can catch a lot more downloads doing this, along with appease the people who use this mod.

**Comment by HyCraftHD** [comment] 2021-12-01 13:58
You can check out the unofficial 1.17.1 fabric port here: https://github.com/Waterpicker/Music-Player
(Need to build it your self)

Maybe in 1.18 I might consider an official port, but don't quote me on that.

**Comment by HyCraftHD** [comment] 2022-01-09 23:30
Duplicate of #269

**Closed as completed** 2022-01-09 23:31 UTC
Labels: enhancement

**Comment by HyCraftHD** [comment] 2022-06-21 23:45
Ported for 1.18.2 and 1.19: See here: https://github.com/MC-U-Team/Music-Player-Fabric
