### ISSUE TITLE
1.15.2 Youtube Player Problem

### ISSUE THREAD

**Issue by MLSPR0** [MC-U-Team/Music-Player#60] opened 2020-07-19 14:18 UTC
The Bug
Basically if I search for something in the Youtube search Bar it says that 'matches not found' this is similar tosome other issue reported by another Player for 1.12 so... Yeah ehh fix it and thx for making such a great mod. have a nice :) if you need more info plz contact at MLSPro#4016 thx...ok

**Comment by HyCraftHD** [comment] 2020-07-19 14:46
Duplicate of #59

**Comment by HyCraftHD** [comment] 2020-07-23 14:28
Use these versions:
![grafik](https://user-images.githubusercontent.com/7681220/88298493-86e46d80-cd01-11ea-83c9-57da4ed90d18.png)

**Closed as completed by HyCraftHD** 2020-07-23 14:28 UTC
Labels: bug, duplicate
