### ISSUE TITLE
1.12.2 crashes on opening 

### ISSUE THREAD

**Issue by Moose206** [MC-U-Team/Music-Player#58] opened 2020-07-06 22:06 UTC
I have my own mod pack, and when i added this mod it crashed on opening, i dont understand anything on the crash report, I'd appreciate if someone can explain the cause
[crash-2020-07-06_15.00.29-client.txt](https://github.com/MC-U-Team/Music-Player/files/4881419/crash-2020-07-06_15.00.29-client.txt)

**Comment by HyCraftHD** [comment] 2020-07-06 22:11
You seem to have downloaded the wrong version. Do not use the dev version. Use the normal ones.
![grafik](https://user-images.githubusercontent.com/7681220/86654584-58b71c00-bfe6-11ea-878a-c206776d526f.png)

**Comment by HyCraftHD** [comment] 2020-07-10 15:32
The problem is not the music player mod, so I'll close this issue. If the issue persists please reopen

**Closed as completed** 2020-07-10 15:32 UTC
Labels: bug
