### ISSUE TITLE
[1.16.5]  internalPlaylist config option does nothing

### ISSUE THREAD

**Issue by maugameslol** [MC-U-Team/Music-Player#729] opened 2023-06-03 01:53 UTC
### Bug description and reproduction steps

Setting "internalPlaylists = true" in the musicplayer-client.toml file does not create a folder in the config folder, and still creates and loads playlists from AppData/Roaming/mc-u-team/musicplayer. 
I do have my modpack instance on a drive other than the C:/ Drive and I am using GDLauncher for managing my modpacks, if that matters.

### Log files and Screenshots

[latest.log](https://github.com/MC-U-Team/Music-Player/files/11640363/latest.log)

### Used minecraft version

1.16.x

### Used forge version

36.2.39

### Used mod version

2.3.2.200

**Comment by HyCraftHD** [comment] 2023-06-14 22:24
Cannot reproduce. How does your config file look like?

**Comment by HyCraftHD** [comment] 2023-07-20 23:23
Closing because not response. When the issue still persists please reopen.

**Closed as completed by HyCraftHD** 2023-07-20 23:23 UTC
Labels: bug
