### ISSUE TITLE
[1.16.4] Music Player has faild to load correctly

### ISSUE THREAD

**Issue by Ischtaratu** [MC-U-Team/Music-Player#97] opened 2020-11-23 03:13 UTC
**Describe the bug**
Mod loading error has occurred

**To Reproduce**
install mod, and load Minecraft. It will crash on loading

**Expected behavior**
no crash ? 

**Screenshots**
see attachment MC Crashlog

**Versions**
- Mod version: 2.2.1.106
- Minecraft version: 1.16.4
- Forge version: 35.1.0
- UTeamCore version: 3.1.13.187

**Log (if crash occures)**
[crash-2020-11-23_04.04.48-fml.txt](https://github.com/MC-U-Team/Music-Player/files/5580971/crash-2020-11-23_04.04.48-fml.txt)

**Comment by HyCraftHD** [comment] 2020-12-02 21:54
Do you have a full debug.log?
Can you try with java 8?
Or Java 11 and Java 14 should work as I have tested them

**Comment by Ischtaratu** [comment] 2020-12-05 20:54
sorry for delay
1. ... full debug log see attached ... 
2. yes, Java 8 works but i would like to run my hole system incl. jdk with a more modern environment ... 
3. Java 8 works, Java 13 crash, Java 14 crash, java 15 crash ... i have no idea .. :(

[crash-2020-12-05_21.45.14-fml.txt](https://github.com/MC-U-Team/Music-Player/files/5647857/crash-2020-12-05_21.45.14-fml.txt)
[debug.log](https://github.com/MC-U-Team/Music-Player/files/5647858/debug.log)

**Comment by Ischtaratu** [comment] 2020-12-05 20:55
Next i will try java 11 asap

**Comment by HyCraftHD** [comment] 2020-12-06 01:07
> sorry for delay

No worries. Thanks for for logs and tests.
Need to find a way to reproduce this, as in my tests it worked. Are you using the normal openjdk from oracle or adoptopenjdk with the hotspot vm?

**Comment by Ischtaratu** [comment] 2020-12-10 02:48
https://openjdk.java.net/

- openjdk-14+36_windows-x64_bin.zip
- openjdk-13+33_windows-x64_bin.zip
- and so on ...

**Comment by Ischtaratu** [comment] 2021-01-04 10:34
New year, new thoughts!
I only use the portable version of OpenJDK without installation. Could this make a difference? Or maybe a missing% HOME% variable or something?

Earlier I programmed a few smaller mods for Minecraft myself. However, that was still in v1.7 times. So at least I still have the basic surroundings in mind.

Is there anything else I can check? Let me know! I'll try to have a look every week.

**Comment by HyCraftHD** [comment] 2021-01-17 23:04
Happy new year!

Well I'm not quite sure what can cause this because I cannot reproduce this issue ...
Probably its because the jdk has some diffrent internals, as the classloader "hack" use some undocumented internal fields.

My time is currently limited, but I plan to remove that classloader hack and shade the necessary libraries into the jar itself. That removes the whole classloader hack and should resolve the issue.

The music player libraries are loaded into a separate classloader without any reflection / unsafe hacks which should not be affected.

After the change to shading this should be removed
https://github.com/MC-U-Team/Music-Player/blob/5a33d3e32e0350857b8d35ebd2923d0cc4dcb092/src/main/java/info/u_team/music_player/dependency/DependencyManager.java#L84-L98
and these libraries should be shaded instead:
https://github.com/MC-U-Team/Music-Player/blob/5a33d3e32e0350857b8d35ebd2923d0cc4dcb092/build.gradle#L166-L169

**Comment by HyCraftHD** [comment] 2021-01-26 16:29
Fixed by removing the class loader hack.
Here is the build: https://www.curseforge.com/minecraft/mc-mods/music-player/files/3182247

**Closed as completed by HyCraftHD** 2021-01-26 16:29 UTC
Labels: bug
